name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a compatible version (>= 16.14.0)
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy
        # Add your deployment steps here (e.g., uploading to a server or deploying to a service like Vercel/Netlify)
        run: echo "Deploy step here"

      - name: Update GitHub About section
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PATCH \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO \
          -d '{"homepage":"https://chandanmahapatra.github.io/india-map-test"}'
